### ISSUE TITLE
problem about command 'npm run api'

### ISSUE THREAD

**Issue by doubleDragon** [0xProject/connect-starter-project#2]
localhost:connect-starter-project wsl$ npm run api

> 0xConnectStarterProject@0.0.0 api /Users/wsl/workspace/js/connect-starter-project
> npm run build; node ./lib/server.js

> 0xConnectStarterProject@0.0.0 build /Users/wsl/workspace/js/connect-starter-project
> tsc

../../../node_modules/@types/jquery/index.d.ts(39,15): error TS2304: Cannot find name 'Event'.
../../../node_modules/@types/jquery/index.d.ts(43,41): error TS2304: Cannot find name 'Node'.
../../../node_modules/@types/jquery/index.d.ts(43,48): error TS2304: Cannot find name 'HTMLElement'.
../../../node_modules/@types/jquery/index.d.ts(93,55): error TS2304: Cannot find name 'Node'.
../../../node_modules/@types/jquery/index.d.ts(126,57): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(135,42): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(135,52): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(138,23): error TS2304: Cannot find name 'Node'.
../../../node_modules/@types/jquery/index.d.ts(138,30): error TS2304: Cannot find name 'HTMLElement'.
../../../node_modules/@types/jquery/index.d.ts(138,51): error TS2304: Cannot find name 'Window'.
../../../node_modules/@types/jquery/index.d.ts(154,90): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(156,17): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(230,25): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(230,45): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(231,15): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(241,19): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(251,22): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(262,19): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(271,22): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(552,22): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(628,32): error TS2304: Cannot find name 'Window'.
../../../node_modules/@types/jquery/index.d.ts(636,20): error TS2304: Cannot find name 'Node'.
../../../node_modules/@types/jquery/index.d.ts(720,38): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(730,51): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(747,29): error TS2304: Cannot find name 'XMLDocument'.
../../../node_modules/@types/jquery/index.d.ts(2809,21): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(2826,25): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(2884,22): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(2894,26): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(2961,35): error TS2304: Cannot find name 'Node'.
../../../node_modules/@types/jquery/index.d.ts(2961,42): error TS2304: Cannot find name 'HTMLElement'.
../../../node_modules/@types/jquery/index.d.ts(2985,45): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(2997,56): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3046,34): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3046,64): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3054,31): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3054,61): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3062,30): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3062,60): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3070,31): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3078,30): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3086,33): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3086,63): error TS2304: Cannot find name 'Document'.
../../../node_modules/@types/jquery/index.d.ts(3162,79): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3343,49): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3355,41): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3362,35): error TS2304: Cannot find name 'Text'.
../../../node_modules/@types/jquery/index.d.ts(3362,42): error TS2304: Cannot find name 'Comment'.
../../../node_modules/@types/jquery/index.d.ts(3721,59): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3732,38): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3826,28): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3926,39): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3975,82): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3984,83): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(3999,55): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4247,44): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4260,56): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4588,47): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4624,80): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4653,44): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4726,35): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4734,35): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4761,45): error TS2304: Cannot find name 'Node'.
../../../node_modules/@types/jquery/index.d.ts(4823,70): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(4834,77): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(5342,65): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(5355,68): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(5368,70): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(5368,143): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(5375,17): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(5375,27): error TS2304: Cannot find name 'Text'.
../../../node_modules/@types/jquery/index.d.ts(5375,34): error TS2304: Cannot find name 'Comment'.
../../../node_modules/@types/jquery/index.d.ts(5694,21): error TS2304: Cannot find name 'XMLHttpRequest'.
../../../node_modules/@types/jquery/index.d.ts(6123,50): error TS2304: Cannot find name 'XMLHttpRequest'.
../../../node_modules/@types/jquery/index.d.ts(6143,14): error TS2304: Cannot find name 'XMLHttpRequest'.
../../../node_modules/@types/jquery/index.d.ts(6145,22): error TS2304: Cannot find name 'XMLHttpRequest'.
../../../node_modules/@types/jquery/index.d.ts(7523,37): error TS2304: Cannot find name 'EventTarget'.
../../../node_modules/@types/jquery/index.d.ts(7633,31): error TS2304: Cannot find name 'EventTarget'.
../../../node_modules/@types/jquery/index.d.ts(7634,44): error TS2304: Cannot find name 'PointerEvent'.
../../../node_modules/@types/jquery/index.d.ts(7634,59): error TS2304: Cannot find name 'KeyboardEvent'.
../../../node_modules/@types/jquery/index.d.ts(7634,75): error TS2304: Cannot find name 'TouchEvent'.
../../../node_modules/@types/jquery/index.d.ts(7682,51): error TS2304: Cannot find name 'EventTarget'.
../../../node_modules/@types/jquery/index.d.ts(7836,55): error TS2304: Cannot find name 'EventTarget'.
../../../node_modules/@types/jquery/index.d.ts(7839,64): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(7874,41): error TS2304: Cannot find name 'Event'.
../../../node_modules/@types/jquery/index.d.ts(7879,20): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(7889,21): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(7914,20): error TS2304: Cannot find name 'Event'.
../../../node_modules/@types/jquery/index.d.ts(7924,20): error TS2304: Cannot find name 'Element'.
../../../node_modules/@types/jquery/index.d.ts(7944,13): error TS2304: Cannot find name 'Element'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! 0xConnectStarterProject@0.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the 0xConnectStarterProject@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wsl/.npm/_logs/2018-01-05T04_49_17_271Z-debug.log
Standard relayer API (HTTP) listening on port 3000!
Standard relayer API (WS) listening on port 3001!

**Comment by doubleDragon** [comment]
The command 'npm run tutorial1'  get some error information too.How to fix it?

**Comment by doubleDragon** [comment]
OS X 10.11.6 
npm version:5.6.0

**Comment by BMillman19** [comment]
@doubleDragon I think my commit here: https://github.com/0xProject/connect-starter-project/commit/e043761c9396afb30bc3b3730d0f22840b96f9a5 may have fixed it, please let me know if that works for you

**Comment by doubleDragon** [comment]
@BMillman19  thanks for your help.  [e043761](https://github.com/0xProject/connect-starter-project/commit/e043761c9396afb30bc3b3730d0f22840b96f9a5) worked.
